version: "2"
services:
  web:
    restart: always
    build: .
    image: metaf_app:latest
    container_name: metaf_app
    ports:
      - 5000:5000
    env_file:
      - web.env
    network_mode: bridge
    links:
      - excel:excel
    command: gunicorn -w 2 -b :5000 wdc:app
    external_links:
      - redis:redis
  excel:
    build:
      context: .
    container_name: metaf_service_excel
    restart: always
    network_mode: bridge
    ports:
      - 5001
    command: python services/metaf_excel.py
  redis:
    image: redis:latest